# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ master ]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout code
    - name: Check out code
      uses: actions/checkout@master
      
    # Building code
    - name: Build Hugo
      uses: lowply/build-hugo@v0.0.2
      
    # Deploying to Firebase
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: 1//05G9LjcOVyNi3CgYIARAAGAUSNwF-L9IrxVrrfSQN3k1F7DKU2pQOGX-QLTYqDUVQaJF8k1Yz_CS9yt0PkswtIH1vjv4ILAMWDv0
        FIREBASE_PROJECT: friendlychat-84bf3
    
    
